# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.1'
use_frameworks!

target 'tumblerLab' do
    pod 'AlamofireImage', '~> 3.5'
end